version: '3'

services:

  rc_node1:
    image: redis:${REDIS_VERSION}
    container_name: rc_node1
    hostname: rc_node1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./container-data/rc-node1:/data   
      - ./cluster_node.conf:/usr/local/etc/redis/redis.conf          
    ports:
      - ${REDIS_PORT1}:6379
    healthcheck:
      test: [ "CMD", "redis-cli","-p","6379","-a","${REDIS_PASSWORD}"]
      timeout: 10s
      interval: 3s
      retries: 10
    networks:
      network_redis_cluster:
        ipv4_address: 172.30.0.11

  rc_node2:
    image: redis:${REDIS_VERSION}
    container_name: rc_node2
    hostname: rc_node2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./container-data/rc-node2:/data      
      - ./cluster_node.conf:/usr/local/etc/redis/redis.conf          
    ports:
      - ${REDIS_PORT2}:6379
    healthcheck:
      test: [ "CMD", "redis-cli","-p","6379","-a","${REDIS_PASSWORD}"]
      timeout: 10s
      interval: 3s
      retries: 10    
    networks:
      network_redis_cluster:
        ipv4_address: 172.30.0.12

  rc_node3:
    image: redis:${REDIS_VERSION}
    container_name: rc_node3
    hostname: rc_node3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./container-data/rc-node3:/data    
      - ./cluster_node.conf:/usr/local/etc/redis/redis.conf          
    ports:
      - ${REDIS_PORT3}:6379      
    healthcheck:
      test: [ "CMD", "redis-cli","-p","6379","-a","${REDIS_PASSWORD}"]
      timeout: 10s
      interval: 3s
      retries: 10    
    networks:
      network_redis_cluster:
        ipv4_address: 172.30.0.13   
      
  rc_node4:
    image: redis:${REDIS_VERSION}
    container_name: rc_node4
    hostname: rc_node4
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./container-data/rc-node4:/data    
      - ./cluster_node.conf:/usr/local/etc/redis/redis.conf           
    ports:
      - ${REDIS_PORT4}:6379      
    healthcheck:
      test: [ "CMD", "redis-cli","-p","6379","-a","${REDIS_PASSWORD}"]
      timeout: 10s
      interval: 3s
      retries: 10    
    networks:
      network_redis_cluster:
        ipv4_address: 172.30.0.14

  rc_node5:
    image: redis:${REDIS_VERSION}
    container_name: rc_node5
    hostname: rc_node5
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./container-data/rc-node5:/data      
      - ./cluster_node.conf:/usr/local/etc/redis/redis.conf          
    ports:
      - ${REDIS_PORT5}:6379      
    healthcheck:
      test: [ "CMD", "redis-cli","-p","6379","-a","${REDIS_PASSWORD}"]
      timeout: 10s
      interval: 3s
      retries: 10    
    networks:
      network_redis_cluster:
        ipv4_address: 172.30.0.15  

  rc_node6:
    image: redis:${REDIS_VERSION}
    container_name: rc_node6
    hostname: rc_node6
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./container-data/rc-node6:/data     
      - ./cluster_node.conf:/usr/local/etc/redis/redis.conf          
    ports:
      - ${REDIS_PORT6}:6379      
    healthcheck:
      test: [ "CMD", "redis-cli","-p","6379","-a","${REDIS_PASSWORD}"]
      timeout: 10s
      interval: 3s
      retries: 10                      
    networks:
      network_redis_cluster:
        ipv4_address: 172.30.0.16  

  cluster_helper:
    image: redis:${REDIS_VERSION}
    container_name: cluster_helper
    hostname: cluster_helper
    command: redis-cli -a ${REDIS_PASSWORD} --cluster create 172.30.0.11:6379 172.30.0.12:6379 172.30.0.13:6379 172.30.0.14:6379 172.30.0.15:6379 172.30.0.16:6379 --cluster-replicas 1 --cluster-yes
    depends_on:
      rc_node1: 
        condition: service_healthy
      rc_node2: 
        condition: service_healthy
      rc_node3:
        condition: service_healthy
      rc_node4:
        condition: service_healthy
      rc_node5: 
        condition: service_healthy
      rc_node6: 
        condition: service_healthy
    networks:
      network_redis_cluster:
        ipv4_address: 172.30.0.17                 

networks:
  network_redis_cluster:
    name: network_redis_cluster
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1